FROM bitnami/spark:latest

# Switch to the root user to perform installation tasks
USER root

# Create missing directories and install Jupyter Notebook
RUN mkdir -p /var/lib/apt/lists/partial && \
    apt-get update && apt-get install -y python3-pip && \
    pip3 install jupyter && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Switch back to the default non-root user
USER 1001

# Set the command to start Jupyter Notebook
CMD ["jupyter", "notebook", "--ip", "0.0.0.0", "--port", "8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
